#!/bin/sh

TARGET=$(ls target/*.jar 2>/dev/null)
echo "alkalog: TARGET=" $TARGET
if [ -z "$TARGET" ]; then
    echo "No jar file in target/, try 'mvn package'".
    exit 1
fi
if [ ! .mvn-classpath -nt pom.xml ]; then
  echo "alkalog: .mvn-classpath -nt pom.xml=" `.mvn-classpath -nt pom.xml`
  mvn dependency:build-classpath -Dmdep.outputFile=.mvn-classpath -q
fi

CP=$(cat .mvn-classpath)
echo "alkalog: CP=" $CP
java -cp $TARGET:$CP com.github.javicho21.main.Main "$@"
